package com.agrigov.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDate;

import com.agrigov.enums.SchemeStatus;

/**
 * Request DTO for creating/updating a PolicyScheme.
 * ERD: PolicyScheme(SchemeID, Title, Description, StartDate, EndDate, Budget, Status)
 * Note: SchemeID is generated by DB; not part of the request.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class PolicySchemeRequest {
	//List of fields getting in request.
    @NotBlank
    private String title;

    private String description;

    private LocalDate startDate;

    private LocalDate endDate;

    @NotNull
    private Double budget;
    private SchemeStatus status;
}