spring.config.import=optional:configserver:
spring.application.name=APIGateway
server.port=9091

jwt.access.secret=DTFit9H2jFl8rrXRNjvTgjknNTHnblP4f7R2aGEP2eqA02iTXwZqvJ8csCZ5SmtN
jwt.access.ttl-seconds=900

spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://AUTHENTICATIONSERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**


spring.cloud.gateway.server.webflux.routes[1].id=auth-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://AUTHENTICATIONSERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/audit/**

spring.cloud.gateway.server.webflux.routes[2].id=projectservice
spring.cloud.gateway.server.webflux.routes[2].predicates=Path=/api/rural-projects/**
spring.cloud.gateway.server.webflux.routes[2].uri=lb://projectservice
 
spring.cloud.gateway.server.webflux.routes[3].id=complianceservice
spring.cloud.gateway.server.webflux.routes[3].predicates=Path=/api/**
spring.cloud.gateway.server.webflux.routes[3].uri=lb://complianceservice
spring.cloud.config.import-check.enabled=false
eureka.instance.prefer-ip-address=true
