spring.application.name=APIGateway
server.port=9091
 
spring.cloud.gateway.server.webflux.routes[0].id=projectservice
spring.cloud.gateway.server.webflux.routes[0].predicates=Path=/api/rural-projects/**
spring.cloud.gateway.server.webflux.routes[0].uri=lb://projectservice
 
spring.cloud.gateway.server.webflux.routes[1].id=complianceservice
spring.cloud.gateway.server.webflux.routes[1].predicates=Path=/api/**
spring.cloud.gateway.server.webflux.routes[1].uri=lb://complianceservice
spring.cloud.config.import-check.enabled=false
eureka.instance.prefer-ip-address=true
