spring.application.name=notificationservice
server.port=1235

# Database connection
spring.datasource.url=jdbc:mysql://localhost:3306/notificationdb?createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.password=Gaurav@2401
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate properties
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.format-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# File upload
file.upload-dir=uploads

# Actuator endpoints
management.endpoints.web.exposure.include=*

# Mail configuration
spring.mail.host=smtp.gmail.com
#Use port 2525 if 587 is not working
spring.mail.port=587
spring.mail.username=agrigovnotify@gmail.com
spring.mail.password=grisokrawajsnylf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT
#jwt.access.secret=DTFit9H2jFl8rrXRNjvTgjknNTHnblP4f7R2aGEP2eqA02iTXwZqvJ8csCZ5SmtN
#jwt.refresh.secret=3df8kJopGIEHFiDMcT342EmYcEmw6sZr59DB0788HFBBZf86CffnQU3gnpVNiZfJ
#jwt.access.ttl-seconds=900
#jwt.refresh.ttl-seconds=2592000
#jwt.refresh.rotate=true

# Eureka client configuration
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Config server import
spring.config.import=configserver:http://localhost:8711


#Disable spring security
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
